FROM python:3.12

WORKDIR /app
COPY . .
RUN mkdir -p /app/data/training/raw
COPY data/training/raw/train.csv.zip /app/data/training/raw/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["bash", "/app/docker/run_train_pipeline.sh"]
