FROM python:3.12

WORKDIR /app
COPY . .
RUN mkdir -p /app/data/raw
COPY data/raw/test.csv.zip /app/data/raw/

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install fastapi uvicorn prometheus-client

EXPOSE 8000
CMD ["uvicorn", "src.inference.api_service:app", "--host", "0.0.0.0", "--port", "8000"]
