FROM python:3.12

WORKDIR /app
COPY . .
ENV PYTHONPATH=/app
RUN pip install --no-cache-dir streamlit joblib requests pandas plotly

EXPOSE 8501
CMD ["streamlit", "run", "src/inference/client.py", "--server.address=0.0.0.0", "--server.port=8501"]
